### ISSUE TITLE
No song listings

### ISSUE THREAD

**Issue by nomego** [SharkHunter/GSPMS#2]
Not sure if Grooveshark has changed anything in their setup, but I don't get any song listings in any category or character (Albums/A, Songs/M, Artists/P, etc).

Known issue or am I doing something wrong?

**Comment by nomego** [comment]
This is all I get in debug:

Grooveshark country "country":{"ID":"190","CC1":"0","CC2":"0","CC3":"2305843009213693952","CC4":"0","IPR":"10339"}

**Comment by SharkHunter** [comment]
Yes they've changed something. This time I think it is a larger rewrite than the last times. When I get time from all other projrct this will be looked into. If someone is faster than me pls do a pull request. The changes are probably in the GS core (gs.java)...

**Comment by nomego** [comment]
Are you currently using their API (http://www.grooveshark.com/api) ?

Or have you tried getting API access?

**Comment by SharkHunter** [comment]
Nope this was made pre grooveshark official API and more of an underground activity, and I'm not sure grooveshark will be 100% pleased with the prospect of the stream being re-streamed (or maybe they don't care).

**Comment by nomego** [comment]
It shouldn't hurt to ask?

For me, if I can use my home theater system as well as my computer to listen to music from the same source, I don't think I'll be that far from getting an "Anywhere" account to be able to use it on my phone as well..

So, making GSPMS work would increase the probability of me being a paying customer..

**Comment by SharkHunter** [comment]
I had a look and as it looks now the fix looks easy. But then when you open pandoras box you don't know right?

I'll look into the gsapi stuff but I think it is quite some rework.

**Comment by nomego** [comment]
Cool, can't wait to try it out!

**Comment by SharkHunter** [comment]
Fixed with new 0.41 version. Enjoy!

**Comment by nomego** [comment]
Perfect, will try it out as soon as I get home!

**Comment by nomego** [comment]
Hmm.. now I get tracks in "Popular" but nothing in A/B/C/etc folders under Artists/Albums/Songs.

Also, when I try to play a song, nothing happens, until the PS3 finally says "Data type not supported".

Log:

Private debug started

Gs 0.41 using path /home/pk/gs_data tiny mode true init delay 3000 zero_fill false

Grooveshark country "country":{"ID":"190","CC1":"0","CC2":"0","CC3":"2305843009213693952","CC4":"0","IPR":"10339"}

GSSong stream data fetched Song: E.T. Album: Teenage Dream Artist: Katy Perry SongId: 26770147 plays  trackNum 8

GSSong stream data true key 35b1d8cc02c27b3b7f75deb1293d95ae96949f41_4e42dc78_1987ae3_1b62ad6_2788926f_1.

GSSong posted request streamKey=35b1d8cc02c27b3b7f75deb1293d95ae96949f41_4e42dc78_1987ae3_1b62ad6_2788926f_1 to url http://stream67-he.grooveshark.com/stream.php cont len 4956577

GSSong start download thread

GSSong start reading response

GSSong download complete

**Comment by SharkHunter** [comment]
The A/B/C folders are the (rather) primitive search system (https://github.com/SharkHunter/GSPMS/wiki/Search-System). As for the rest what it shows is that it successfully manages to download the song. However your render might have given up. Try and fiddle with the init_delay setting. 3000 works for me.

**Comment by y-nk** [comment]
I've got the same issue as nomego : the popular playlist works fine, and i can play it ; no search of any type is working, and i don't have any kind of big error in the log files...

**Comment by y-nk** [comment]
I activated the private log file, and have this line when trying to play a popular song :
GsSong post exception java.lang.IllegalArgumentException: protocol = http host = null

It looks related to this https://github.com/SharkHunter/GSPMS/blob/master/src/net/pms/external/GsSong.java#L120
