### ISSUE TITLE
HTTP host == null on GSSong

### ISSUE THREAD

**Issue by y-nk** [SharkHunter/GSPMS#4]
I activated the private log file, and have this line when trying to play a "popular" song :
GsSong post exception java.lang.IllegalArgumentException: protocol = http host = null

It looks related to this https://github.com/SharkHunter/GSPMS/blob/master/src/net/pms/external/GsSong.java#L120

Also, i noticed that i can't search anything, but i think it's related somehow.

Thanks

**Comment by favioe** [comment]
Same problem here. Error log is:
INFO  2012-06-10 02:34:03.277 [New I/O server worker #1-4] GsSong post exception java.lang.IllegalArgumentException: protocol = http host = null

I couldn't play any song...
SO: Ubuntu 12.04
PMS: 1.52.1
gs_plugin_046.jar

PMS.conf:
gs_plugin.init_delay = 6000
gs_plugin.path = /home/myuser/Downloads/grooveshark
gs_plugin.tiny = false  # I tried with true and false

Thanks!
